# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piloto',
            old_name='numero_documento_identificacion',
            new_name='dni',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='documento_identificacion',
        ),
        migrations.AlterField(
            model_name='piloto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='observacion',
            field=models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Observación'),
        ),
    ]
