# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 18:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0002_auto_20161130_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='dni',
            field=models.CharField(db_index=True, help_text='Escribir número documento identificación.', max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(8)], verbose_name='D.N.I.'),
        ),
    ]
