# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0004_remove_piloto_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piloto',
            name='fecha_cese',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='fecha_fin_contratacion',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='fecha_inicio_contratacion',
        ),
    ]
