# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='via',
            name='direccion_ip',
        ),
        migrations.RemoveField(
            model_name='via',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='via',
            name='fecha_ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='via',
            name='nombre_host',
        ),
        migrations.RemoveField(
            model_name='via',
            name='ultimo_direccion_ip',
        ),
        migrations.RemoveField(
            model_name='via',
            name='ultimo_nombre_host',
        ),
        migrations.RemoveField(
            model_name='via',
            name='ultimo_usuario_editor',
        ),
        migrations.RemoveField(
            model_name='via',
            name='usuario_creador',
        ),
    ]
