# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos_modulos', '0004_grupomodulo_slug'),
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoModuloMenuSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_modulo', models.SmallIntegerField(default=0)),
                ('orden_menu', models.SmallIntegerField(default=0)),
                ('orden_sub_menu', models.SmallIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, help_text='Subir imagen. (Opcional)', null=True, upload_to='')),
                ('url', models.URLField(db_index=True, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Observación')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('grupo_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos_modulos.GrupoModulo')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
            options={
                'verbose_name': 'Catalogo Módulo Menu Sub Menu',
                'verbose_name_plural': 'Catalogos Módulos Menus Sub Menus',
                'ordering': ('orden_modulo', 'orden_menu', 'orden_sub_menu'),
                'db_table': 'Catalogos_Modulos_Menus_Sub_Menus',
            },
        ),
    ]
