# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulos', '0001_initial'),
        ('sub_menus', '0001_initial'),
        ('catalogos_modulos_menus_sub_menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogomodulomenusubmenu',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.Modulo'),
        ),
        migrations.AddField(
            model_name='catalogomodulomenusubmenu',
            name='sub_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_menus.SubMenu'),
        ),
    ]
