# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-22 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos_modulos_menus_sub_menus', '0003_catalogomodulomenusubmenu_menu'),
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogomodulomenusubmenu',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.Modulo'),
        ),
    ]
