# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos_modulos_menus_sub_menus', '0006_auto_20161122_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='direccion_ip',
        ),
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='fecha_ultima_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='nombre_host',
        ),
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='ultimo_direccion_ip',
        ),
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='ultimo_nombre_host',
        ),
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='ultimo_usuario_editor',
        ),
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='usuario_creador',
        ),
    ]
