# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos_modulos_menus_sub_menus', '0008_catalogomodulomenusubmenu_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogomodulomenusubmenu',
            name='observacion',
        ),
    ]
