# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aeronaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAeronaveParte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Ubicación')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeronaves.Aeronave')),
            ],
            options={
                'verbose_name': 'Catalogo Aeronave Parte',
                'db_table': 'Catalogos_Aeronaves_Partes',
                'verbose_name_plural': 'Catalogos Aeronaves Partes',
            },
        ),
    ]
