# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos_aeronaves_partes', '0001_initial'),
        ('partes_aeronaves', '0003_auto_20161129_1552'),
        ('averias', '0003_auto_20161129_1552'),
        ('catalogos_aeronaves_partes_averias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoaeronaveparte',
            name='averia',
            field=models.ManyToManyField(through='catalogos_aeronaves_partes_averias.CatalogoAeronaveParteAveria', to='averias.Averia'),
        ),
        migrations.AddField(
            model_name='catalogoaeronaveparte',
            name='parte_aeronave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partes_aeronaves.ParteAeronave'),
        ),
    ]
