# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos_aeronaves_partes', '0002_auto_20161129_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogoaeronaveparte',
            options={'verbose_name': 'Catalogo Aeronave Parte', 'verbose_name_plural': 'Catalogos Aeronaves Partes'},
        ),
        migrations.RenameField(
            model_name='catalogoaeronaveparte',
            old_name='descripcion',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='catalogoaeronaveparte',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='catalogoaeronaveparte',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='catalogoaeronaveparte',
            name='orden_aeronave',
        ),
        migrations.RemoveField(
            model_name='catalogoaeronaveparte',
            name='orden_parte_aeronave',
        ),
    ]
