# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipos_empleados', '0001_initial'),
        ('soluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='tipo_especialista',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tipos_empleados.TipoEmpleado'),
            preserve_default=False,
        ),
    ]
