# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soluciones', '0002_solucion_tipo_especialista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solucion',
            old_name='tipo_especialista',
            new_name='tipo_empleado',
        ),
    ]
