# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 20:23
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distritos', '0004_auto_20161129_1505'),
        ('estados_civiles', '0003_auto_20161129_1505'),
        ('vias', '0002_auto_20161129_1505'),
        ('zonas', '0002_auto_20161129_1505'),
        ('documentos_identificaciones', '0001_initial'),
        ('cargos', '0003_auto_20161129_1523'),
        ('areas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipos_empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(db_index=True, help_text='Escribir apellido paterno.', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)])),
                ('apellido_materno', models.CharField(db_index=True, help_text='Escribir apellido materno.', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)])),
                ('nombre', models.CharField(db_index=True, help_text='Escribir nombre(s).', max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Nombre(s)')),
                ('numero_documento_identificacion', models.CharField(db_index=True, help_text='Escribir número documento identificación.', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)], verbose_name='Número documento identificación')),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=9, verbose_name='Género')),
                ('telefono', models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True, verbose_name='Télefono')),
                ('celular', models.CharField(blank=True, help_text='(Opcional).', max_length=20, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)], verbose_name='Correo electrónico')),
                ('fotografia', models.ImageField(blank=True, default='default/No_Avatar_1.png', help_text='Subir fotografia (Opcional).', null=True, upload_to='fotografias', verbose_name='Avatar (Fotografía)')),
                ('direccion', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)], verbose_name='Dirección')),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Descripción (Empleado)')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Observación (Empleado)')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('fecha_inicio_contratacion', models.DateField(help_text='Seleccionar fecha de inicio de contratación del empleado.', verbose_name='Fecha inicio contratación')),
                ('fecha_fin_contratacion', models.DateField(blank=True, help_text='Seleccionar fecha de final de contratación del empleado.', null=True, verbose_name='Fecha fin contratación')),
                ('fecha_cese', models.DateTimeField(blank=True, help_text='Seleccionar fecha de cese del empleado.', null=True)),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Cargo')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='distritos.Distrito')),
                ('documento_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='documentos_identificaciones.DocumentoIdentificacion', verbose_name='Documento identificación')),
                ('estado_civil', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='estados_civiles.EstadoCivil')),
                ('tipo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_empleados.TipoEmpleado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empleados_related', to=settings.AUTH_USER_MODEL)),
                ('via', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='vias.Via')),
                ('zona', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_empleado_related', to='zonas.Zona')),
            ],
            options={
                'verbose_name': 'Empleado',
                'ordering': ('apellido_paterno',),
                'db_table': 'Empleados',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
