# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_empleado_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_cese',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_fin_contratacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_inicio_contratacion',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos.Cargo', verbose_name='Cargo - Grado'),
        ),
    ]
