# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 20:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos', '0003_auto_20161129_1552'),
        ('colores', '0003_auto_20161129_1552'),
        ('marcas', '0003_auto_20161129_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Escribir el nombre del aeronave.', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('fotografia', models.ImageField(blank=True, default='default/No_Avatar_1.png', help_text='Subir fotografia (Opcional).', null=True, upload_to='fotografias_aviones', verbose_name='Avatar (Fotografía)')),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Descripción (Aeronave)')),
                ('observacion', models.TextField(blank=True, help_text='(Opcional).', null=True, verbose_name='Observación (Aeronave)')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colores.Color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcas.Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Modelo')),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
                'ordering': ('nombre',),
                'db_table': 'Aeronaves',
            },
        ),
    ]
