# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 23:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeronaves', '0002_auto_20161207_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='numero_cola_aeronave',
            field=models.CharField(db_index=True, default=0, help_text='Escribir el numero cola de aeronave .', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
