# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeronaves', '0002_auto_20161129_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='activo',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True),
        ),
    ]
