# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aeronaves', '0003_aeronave_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeronave',
            name='color',
        ),
        migrations.RemoveField(
            model_name='aeronave',
            name='observacion',
        ),
    ]
