# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcas', '0003_auto_20161129_1552'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marca',
            table='Marcas',
        ),
    ]
