# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos_aeronaves_partes_averias', '0001_initial'),
        ('empleados', '0001_initial'),
        ('catalogos_aeronaves_partes_averias_empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoaeronaveparteaveria',
            name='empleado',
            field=models.ManyToManyField(through='catalogos_aeronaves_partes_averias_empleados.CatalogoAeronaveParteAveriaEmpleado', to='empleados.Empleado'),
        ),
    ]
