# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos_aeronaves_partes_averias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAeronaveParteAveriaSolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Descripción')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('catalogo_aeronave_parte_averia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos_aeronaves_partes_averias.CatalogoAeronaveParteAveria')),
            ],
            options={
                'verbose_name': 'Catalogo Aeronave Parte Averia Solucion',
                'db_table': 'Catalogos_Aeronaves_Partes_Averias_Soluciones',
                'verbose_name_plural': 'Catalogos Aeronaves Partes Averias Soluciones',
            },
        ),
    ]
