# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos_aeronaves_partes_averias_soluciones', '0001_initial'),
        ('soluciones', '0003_auto_20161207_1727'),
        ('catalogos_aeronaves_partes_averias_soluciones_empleados', '0001_initial'),
        ('empleados', '0005_auto_20161130_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoaeronaveparteaveriasolucion',
            name='empleado',
            field=models.ManyToManyField(through='catalogos_aeronaves_partes_averias_soluciones_empleados.CatalogoAeronaveParteAveriaSolucionEmpleado', to='empleados.Empleado'),
        ),
        migrations.AddField(
            model_name='catalogoaeronaveparteaveriasolucion',
            name='solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soluciones.Solucion'),
        ),
    ]
