# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aeronaves', '0003_aeronave_numero_cola_aeronave'),
        ('ordenes_vuelos', '0001_initial'),
        ('pilotos', '0006_auto_20161130_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Escribir el nombre de la tripulación.', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('aeronaves', models.ManyToManyField(through='ordenes_vuelos.OrdenVuelo', to='aeronaves.Aeronave')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotos.Piloto')),
            ],
            options={
                'verbose_name': 'Tripulacion',
                'verbose_name_plural': 'Tripulaciones',
                'ordering': ('nombre',),
                'db_table': 'Tripulaciones',
            },
        ),
    ]
