# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotos', '0006_auto_20161130_1406'),
        ('asignaciones_tripulaciones_pilotos', '0001_initial'),
        ('tripulaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripulacion',
            name='piloto',
        ),
        migrations.AddField(
            model_name='tripulacion',
            name='piloto',
            field=models.ManyToManyField(through='asignaciones_tripulaciones_pilotos.AsiganacionTripulacionPiloto', to='pilotos.Piloto'),
        ),
    ]
