# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilotos', '0006_auto_20161130_1406'),
        ('tripulaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsiganacionTripulacionPiloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pilotos.Piloto')),
                ('tripulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripulaciones.Tripulacion')),
            ],
            options={
                'verbose_name': 'Asiganacion Tripulacion Piloto',
                'verbose_name_plural': 'Asiganaciones Tripulaciones Pilotos',
                'db_table': 'Asiganaciones_Tripulaciones_Pilotos',
            },
        ),
    ]
