# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones_tripulaciones_pilotos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsiganacionTripulacionPiloto',
            new_name='AsignacionTripulacionPiloto',
        ),
        migrations.AlterModelOptions(
            name='asignaciontripulacionpiloto',
            options={'verbose_name': 'Asignacion Tripulacion Piloto', 'verbose_name_plural': 'Asignaciones Tripulaciones Pilotos'},
        ),
        migrations.AlterModelTable(
            name='asignaciontripulacionpiloto',
            table='Asignaciones_Tripulaciones_Pilotos',
        ),
    ]
