# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-29 20:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos_identificaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Escribir el nombre de la entidad.', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(255)])),
                ('slogan', models.CharField(blank=True, db_index=True, help_text='Escribir el slogan de la entidad.', max_length=255, null=True)),
                ('siglas', models.CharField(db_index=True, max_length=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)])),
                ('numero_documento_identificacion', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)], verbose_name='Número documento identificación')),
                ('mision', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Misión')),
                ('vision', models.TextField(blank=True, help_text='(Opcional)', null=True, verbose_name='Visión')),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos_entidades')),
                ('activo', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('documento_identificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos_identificaciones.DocumentoIdentificacion', verbose_name='Documento identificación')),
            ],
            options={
                'ordering': ('nombre',),
                'verbose_name': 'Entidad',
                'db_table': 'Entidades',
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
