# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-30 18:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='documento_identificacion',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='mision',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='numero_documento_identificacion',
        ),
        migrations.RemoveField(
            model_name='entidad',
            name='vision',
        ),
        migrations.AddField(
            model_name='entidad',
            name='ruc',
            field=models.CharField(db_index=True, default='', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)], verbose_name='R.U.C.'),
            preserve_default=False,
        ),
    ]
