# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:25
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipos_vuelos', '0001_initial'),
        ('aeronaves', '0003_aeronave_numero_cola_aeronave'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenVuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)])),
                ('mision', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('altura', models.PositiveSmallIntegerField(default=0)),
                ('galon', models.PositiveSmallIntegerField(default=0)),
                ('fecha_vuelo', models.DateTimeField(default=datetime.datetime(2016, 12, 15, 12, 25, 1, 726478))),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aeronaves.Aeronave')),
                ('tipo_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipos_vuelos.TipoVuelo')),
            ],
            options={
                'verbose_name': 'Orden Vuelo',
                'verbose_name_plural': 'Ordenes Vuelos',
                'db_table': 'Ordenes_Vuelos',
            },
        ),
    ]
