# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes_vuelos', '0001_initial'),
        ('tripulaciones', '0001_initial'),
        ('zonas_vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenvuelo',
            name='tripulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripulaciones.Tripulacion'),
        ),
        migrations.AddField(
            model_name='ordenvuelo',
            name='zona_vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zonas_vuelos.ZonaVuelo'),
        ),
    ]
