# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos_aeronaves_partes_averias_soluciones', '0001_initial'),
        ('empleados', '0005_auto_20161130_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAeronaveParteAveriaSolucionEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selecionar', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('catalogos_aeronaves_partes_averias_soluciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos_aeronaves_partes_averias_soluciones.CatalogoAeronaveParteAveriaSolucion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
            ],
            options={
                'verbose_name': 'Catalogo Aeronave Parte Averia Solucion Empleado',
                'db_table': 'Catalogos_Aeronaves_Partes_Averias_Soluciones_Empleados',
                'verbose_name_plural': 'Catalogos Aeronaves Partes Averias Soluciones Empleados',
            },
        ),
    ]
