# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos_aeronaves_partes_averias_soluciones_empleados', '0006_auto_20161215_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoaeronaveparteaveriasolucionempleado',
            name='fecha_diagnostico',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 16, 8, 24, 0, 586739)),
        ),
    ]
